name: sizzle
description: A bitmap/pixel game engine based on Flame
version: 0.1.0
repository: https://github.com/projectitis/sizzle

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame:
    path: D:/Projects/flutter/flame/packages/flame
#    git:
#      url: https://github.com/flame-engine/flame.git
#      path: packages/flame
#  flame: ^1.8.2
  jenny:
    path: D:/Projects/flutter/flame/packages/flame_jenny/jenny
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  meta: ^1.10.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
